FeedVinc.WEB.UI/Controllers/BaseUIController.cs
using FeedVinc.BLL.Services;
using FeedVinc.Common.Services;
using FeedVinc.DAL.ORM.Entities;
using FeedVinc.WEB.UI.Areas.Admin.Models;
using FeedVinc.WEB.UI.Attributes;
using FeedVinc.WEB.UI.MessageFilter;
using FeedVinc.WEB.UI.Models.DTO;
using FeedVinc.WEB.UI.Models.ViewModels;
using FeedVinc.WEB.UI.Models.ViewModels.Account;
using FeedVinc.WEB.UI.Models.ViewModels.Filter;
using FeedVinc.WEB.UI.Models.ViewModels.Home;
using FeedVinc.WEB.UI.Models.ViewModels.Message;
using FeedVinc.WEB.UI.Models.ViewModels.Notification;
using FeedVinc.WEB.UI.Resources;
using FeedVinc.WEB.UI.ShareCommentFactory;
using FeedVinc.WEB.UI.TagManagerService;
using FeedVinc.WEB.UI.UIServices;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using app = FeedVinc.WEB.UI.MvcApplication;

namespace FeedVinc.WEB.UI.Controllers
{
    [LoginControl]
    public class BaseUIController : Controller
    {
        protected UnitOfWork services;
        protected UserVM _currentUser;


        public BaseUIController()
        {
            services = new UnitOfWork();
            _currentUser = UserManagerService.CurrentUser;

        }


        public string GetShareTypeIDString(int shareTypeID)
        {
            switch (shareTypeID)
            {
                case 1:
                    return "user";
                case 2:
                    return "idea";
                case 3:
                    return "project";
                case 4:
                    return "feedback";
                case 5:
                    return "launch";
                default:
                    return "community";
                    break;
            }
        }


        [HttpGet]
        public JsonResult GetContact(string searchText)
        {
            List<MessageContactVM> model = new List<MessageContactVM>();

            if (!String.IsNullOrEmpty(searchText))
            {

                MessageFilterManager manager = new MessageFilterManager(new PublicMessageAccess(services));
                model.AddRange(manager.GetContact(searchText, UserManagerService.CurrentUser.ID));
            }
            else
            {
                MessageFilterManager manager = new MessageFilterManager(new PrivateMessageAccess(services));
                model.AddRange(manager.GetContact(searchText, UserManagerService.CurrentUser.ID));
            }

            return Json(model, JsonRequestBehavior.AllowGet);
        }


        [ChildActionOnly]
        public PartialViewResult GetUserMessage()
        {

            var currentUserID = UserManagerService.CurrentUser.ID;
            var model = new MessageWrapperVM();
            model.LastMessages = new List<MessageVM>();
            model.Contacts = new List<MessageFilter.MessageContactVM>();

            var senderIds = services.appUserMessageRepo.Where(x => x.RecieverID == currentUserID).GroupBy(c => c.SenderID).Select(f => f.Key).ToList();

            foreach (var senderId in senderIds)
            {
                var lastMessage = services.appUserMessageRepo.Where(x => x.SenderID == senderId).OrderByDescending(x => x.ID).Take(1).Select(a => new MessageVM
                {
                    LastMessage = a.Message,
                    LastLook = DateTimeService.GetPrettyDate(a.PostDate, LanguageService.getCurrentLanguage),
                    MessageID = a.ID,
                    SenderID = a.SenderID,
                    ReciverID = a.RecieverID

                }).FirstOrDefault();

                lastMessage.User = services.appUserRepo.Where(x => x.ID == lastMessage.SenderID).Select(a => new MessageUserVM
                {
                    UserName = a.Name + " " + a.SurName,
                    UserProfilePhoto = a.ProfilePhoto

                }).FirstOrDefault();

                lastMessage.MessageDetails = services.appUserMessageRepo.Where(x => (x.RecieverID == currentUserID && x.SenderID == senderId) || (x.SenderID == currentUserID && x.RecieverID == senderId)).Select(a => new MessageDetailVM
                {
                    Message = a.Message,
                    MessageID = a.ID,
                    IsRecieved = a.RecieverID == currentUserID ? true : false,
                    SenderID = lastMessage.SenderID,
                    PrettyPostDate = DateTimeService.GetPrettyDate(a.PostDate, LanguageService.getCurrentLanguage),
                    RecieverID = a.RecieverID


                }).OrderByDescending(x => x.MessageID).ToList();

                model.LastMessages.Add(lastMessage);
            }

            MessageFilterManager manager = new MessageFilterManager(new PrivateMessageAccess(services));
            model.Contacts = manager.GetContact("", currentUserID);



            return PartialView("~/Views/Shared/Partial/_userMessageDropDown.cshtml", model);
        }

        [ChildActionOnly]
        public PartialViewResult GetFollowNotificationTop5()
        {
            var model = services.followNotifyRepo
                .Where(x => x.OwnerID == UserManagerService.CurrentUser.ID)
                .OrderByDescending(x => x.PostDate)
                .Take(10)
                .Select(a => new NotificationFollowVM
                {
                    NotificationName = a.OwnerName,
                    NotificationText = a.NotificationText,
                    Link = a.Link,
                    ProfilePhoto = a.NotificationPhotoPath,
                    PostID = a.ID

                })
            .ToList();



            return PartialView("~/Views/Shared/Partial/_notificationFollowDropDown.cshtml", model);
        }

        [ChildActionOnly]
        public PartialViewResult GetFollowNotification()
        {

            var model = services.followNotifyRepo
                .Where(x => x.OwnerID == UserManagerService.CurrentUser.ID)
                .Select(a => new NotificationFollowVM
                {
                    NotificationName = a.OwnerName,
                    NotificationText = a.NotificationText,
                    Link = a.Link,
                    ProfilePhoto = a.NotificationPhotoPath,
                    PostID = a.ID
                })
            .ToList();

            return PartialView("~/Views/Shared/Partial/Modal/_followerNotificationModal.cshtml", model);
        }

        [ChildActionOnly]
        public PartialViewResult GetDynamicMissionModal()
        {

            var missionIDs = services.ProjectMissionAssignmentRepo
                .Where(x => x.OwnerID == UserManagerService.CurrentUser.ID)
                .ToList().Select(z => z.ProjectMissionID);

            var model = services.ProjectMissionRepo.Where(x => missionIDs.Contains(x.ID)).Select(a => new MissionAssignmentVM
            {
                MissionContent = a.MissionContent,
                PrettyDate = DateTimeService.GetPrettyDate(a.CreateDate, LanguageService.getCurrentLanguage),
                MissionID = a.ID

            }).ToList();


            return PartialView("~/Views/Shared/Partial/Modal/_missionsModal.cshtml", model);
        }

        [HttpPost]
        public JsonResult DeleteMission(int missionid,int userid)
        {
            services.ProjectMissionAssignmentRepo.Remove(x => x.OwnerID == userid && x.ProjectMissionID == missionid);
            services.Commit();

            return Json("OK");
        }

        [ChildActionOnly]
        public PartialViewResult GetDynamicMission()
        {

            var missionIDs = services.ProjectMissionAssignmentRepo
                .Where(x => x.OwnerID == UserManagerService.CurrentUser.ID)
                .ToList().Select(z=> z.ProjectMissionID);

            var model = services.ProjectMissionRepo.Where(x => missionIDs.Contains(x.ID)).Select(a => new MissionAssignmentVM
            {
                MissionContent = a.MissionContent,
                PrettyDate = DateTimeService.GetPrettyDate(a.CreateDate,LanguageService.getCurrentLanguage),
                MissionID = a.ID

            }).ToList();


            return PartialView("~/Views/Shared/Partial/_missionDropDown.cshtml", model);
        }


        [ChildActionOnly]
        public PartialViewResult GetShareNotificationCurrentUserProfile()
        {
            var notificationIDs = services.shareNotifyUserRepo
                .Where(x => x.UserID == UserManagerService.CurrentUser.ID)
                .Select(c => c.NotificationID)
                .ToList();

            var model = services.shareNotifyRepo
                .Where(x => notificationIDs.Contains(x.ID))
                .Select(a => new NotificationShareVM
                {
                    NotificationText = a.NotificationText,
                    ProfilePhotoPath = a.NotificationPhotoPath,
                    SharePrettyDate = DateTimeService.GetPrettyDate(a.PostDate, LanguageService.getCurrentLanguage),
                    ShareNotificationID = a.ID,
                    ShareProfileLink = a.Link,
                    ShareProfileName = a.OwnerName

                })
            .ToList();

            return PartialView("~/Views/Shared/Partial/Modal/_shareNotificationModal.cshtml", model);
        }

        [ChildActionOnly]
        public PartialViewResult GetShareNotificationCurrentUserProfileTop5()
        {
            var notificationIDs = services.shareNotifyUserRepo
              .Where(x => x.UserID == UserManagerService.CurrentUser.ID)
              .Select(c => c.NotificationID)
              .ToList();

            var model = services.shareNotifyRepo
                .Where(x => notificationIDs.Contains(x.ID))
                .OrderByDescending(x => x.PostDate)
                .Take(5)
                .Select(a => new NotificationShareVM
                {
                    NotificationText = a.NotificationText,

FeedVinc.WEB.UI/Views/InvestmentLetter/InvestmentLetterDetail.cshtml
@{
    ViewBag.Title = "InvestmentLetterDetail";
    Layout = "~/Views/Shared/_SiteLayout.cshtml";
}

@using FeedVinc.WEB.UI.UIServices
@using FeedVinc.WEB.UI.Models.ViewModels.InvesterLetter
@model InvestmentLetterDetailVM

@{
    Html.RenderAction("GetNavbar", "BaseUI");
}


<main>
    <section class="container">
        <div class="row">
            <!-- İçerik -->
            <section class="col-lg-12 col-md-12 col-sm-12 col-xs-12 mb30">
                <div class="row">
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                        <div class="investment-letter-wrap">
                            <div>
                                <ul class="alert alert-danger text-center" id="validationMessage" style="display:none;list-style:none;"></ul>
                            </div>
                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 no-padding">
                                <h2>@SiteLanguage.Investment_Letter</h2>
                            </div>
                            <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12 no-padding">
                                <!-- Mobil için Yatırım Sol Menü -->
                                <div class="dropdown visible-xs mmb-20">
                                    <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                                        Bölüm Seç
                                        <span class="caret"></span>
                                    </button>
                                    <ul class="dropdown-menu investment-list-mobile" aria-labelledby="dropdownMenu1">
                                        <li class="active"><a href="#" data-inv-tab="mesaj">Mesaj</a></li>
                                        <li><a href="#" data-inv-tab="proje-kunyesi">Proje Künyesi</a></li>
                                        <li><a href="#" data-inv-tab="musteri-segmenti">Müşteri Segmenti</a></li>
                                        <li><a href="#" data-inv-tab="pazar-potansiyeli">Pazar Potansiyeli</a></li>
                                        <li><a href="#" data-inv-tab="deger-onerisi">Değer Önerisi</a></li>
                                        <li><a href="#" data-inv-tab="yatirim-durumu">Yatırım Durumu</a></li>
                                        <li><a href="#" data-inv-tab="yatirim-beklentisi">Yatırım Bekletisi</a></li>
                                        <li><a href="#" data-inv-tab="ekip-ortaklar">Ekip & Ortaklar</a></li>
                                        <li><a href="#" data-inv-tab="rakip-analizi">Rakip Analizi</a></li>
                                        <li><a href="#" data-inv-tab="finansal-durum">Finansal Durum</a></li>
                                        <li><a href="#" data-inv-tab="mektup-gonder">Mektubu Gönder</a></li>
                                    </ul>
                                </div>

                                <ul class="investment-list box-white hidden-xs">
                                    <li class="active" data-tab-id="1" data-inv-tab="@SiteLanguage._Message">
                                        <a href="javascript:ClickToTab(1)">
                                            <span>1</span>
                                            <p>@SiteLanguage._Message</p>
                                            <div class="inv-check"></div>
                                        </a>
                                    </li>
                                    <li data-tab-id="2" data-inv-tab="@SiteLanguage._ProjectOverview">
                                        <a href="javascript:ClickToTab(2)">
                                            <span>2</span>
                                            <p>@SiteLanguage._ProjectOverview</p>
                                        </a>
                                    </li>
                                    <li data-tab-id="3" data-inv-tab="@SiteLanguage._CustomerSegment">
                                        <a href="javascript:ClickToTab(3)">
                                            <span>3</span>
                                            <p>@SiteLanguage._CustomerSegment</p>
                                        </a>
                                    </li>
                                    <li data-tab-id="4" data-inv-tab="@SiteLanguage._MarketPotential">
                                        <a href="javascript:ClickToTab(4)">
                                            <span>4</span>
                                            <p>@SiteLanguage._MarketPotential</p>
                                        </a>
                                    </li>
                                    <li data-tab-id="5" data-inv-tab="@SiteLanguage._ValueProposition">
                                        <a href="javascript:ClickToTab(5)">
                                            <span>5</span>
                                            <p>@SiteLanguage._ValueProposition</p>
                                        </a>
                                    </li>
                                    <li data-tab-id="6" data-inv-tab="@SiteLanguage._InvestmentStatus">
                                        <a href="javascript:ClickToTab(6)">
                                            <span>6</span>
                                            <p>@SiteLanguage._InvestmentStatus</p>
                                        </a>
                                    </li>
                                    <li data-tab-id="7" data-inv-tab="@SiteLanguage._InvestmentExpactancy">
                                        <a href="javascript:ClickToTab(7)">
                                            <span>7</span>
                                            <p>@SiteLanguage._InvestmentExpactancy</p>
                                        </a>
                                    </li>
                                    <li data-tab-id="8" data-inv-tab="@SiteLanguage._TeamAndCollaborators">
                                        <a href="javascript:ClickToTab(8)">
                                            <span>8</span>
                                            <p>@SiteLanguage._TeamAndCollaborators</p>
                                        </a>
                                    </li>
                                    <li data-tab-id="9" data-inv-tab="@SiteLanguage._CompetitorAnalysis">
                                        <a href="javascript:ClickToTab(9)">
                                            <span>9</span>
                                            <p>@SiteLanguage._CompetitorAnalysis</p>
                                        </a>
                                    </li>
                                    <li data-tab-id="10" data-inv-tab="@SiteLanguage._FinancialCondition">
                                        <a href="javascript:ClickToTab(10)">
                                            <span>10</span>
                                            <p>@SiteLanguage._FinancialCondition</p>
                                        </a>
                                    </li>
                                </ul>
                            </div>
                            <div class="col-lg-9 col-md-9 col-sm-9 col-xs-12 pad-left">
                                <div class="investment-box box-white">
                                    <p class="heading">@SiteLanguage.Dear ,@UserManagerService.CurrentUser.FullName</p>
                                    <p id="_content">@Model.InvestmentLetter.Message</p>
                                    <div class="investment-box-bottom">
                                        <div class="pull-right">
                                            <img src="@Model.Owner.ProfilePhoto" alt="Kullanıcı Profili" />
                                            <div class="investment-info">
                                                <h5>@Model.Owner.UserName</h5>
                                                <p>@Model.Project.ProjectName</p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="investment-buttons">
                                    <button type="button" class="btn btn-default pull-right fs16">Proje Profili</button>
                                    <button type="button" class="btn btn-default pull-right fs16 mr20">Mesaj Gönder</button>
                                    <button type="button" class="btn btn-default pull-right fs16 mr20">App Analytics</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
            <!-- İçerik bitti -->
        </div>
    </section>
</main>

@section scripts{

    <script>

        function ClickToTab(tabid) {

            var element = $(".investment-list").find("[data-tab-id='" + tabid + "']");
            var title = $(element).attr("data-inv-tab");
            $("#title").text("").text(title);

            switch (parseInt(tabid)) {
                case 1:
                    $("#_content").text('@Model.InvestmentLetter.Message');
                    $(".investment-list > li").removeClass("active");
                    $(element).addClass("active");
                    break;
                case 2:
                    $("#_content").text('@Model.InvestmentLetter.CustomerSegment');
                    $(".investment-list > li").removeClass("active");
                    $(element).addClass("active");
                    break;
                case 3:
                    $("#_content").text('@Model.InvestmentLetter.ProjectOverview');
                    $(".investment-list > li").removeClass("active");
                    $(element).addClass("active");
                    break;
                case 4:
                    $("#_content").text('@Model.InvestmentLetter.MarketPotential');
                    $(".investment-list > li").removeClass("active");
                    $(element).addClass("active");
                    break;
                case 5:
                    $("#_content").text('@Model.InvestmentLetter.ValueProposition');
                    $(".investment-list > li").removeClass("active");
                    $(element).addClass("active");
                    break;
                case 6:
                    $("#_content").text('@Model.InvestmentLetter.InvestmentStatus');
                    $(".investment-list > li").removeClass("active");
                    $(element).addClass("active");
                    break;
                case 7:
                    $("#_content").text('@Model.InvestmentLetter.InvestmentExpectancy');
                    $(".investment-list > li").removeClass("active");
                    $(element).addClass("active");
                    break;
                case 8:
                    $("#_content").text('@Model.InvestmentLetter.TeamAndCollaborators');
                    $(".investment-list > li").removeClass("active");
                    $(element).addClass("active");
                    break;
                case 9:
                    $("#_content").text('@Model.InvestmentLetter.CompetitorAnalysis');
                    $(".investment-list > li").removeClass("active");
                    $(element).addClass("active");
                    break;
                case 10:
                    $("#_content").text('@Model.InvestmentLetter.FinancialCondition');
                    $(".investment-list > li").removeClass("active");
                    $(element).addClass("active");
                    break;
                default:

            }
        }

    </script>

}

FeedVinc.WEB.UI/Views/InvestmentLetter/ShowInvestmentLetter.cshtml
@{
    ViewBag.Title = "ShowInvestmentLetter";
    Layout = "~/Views/Shared/_SiteLayout.cshtml";
}


@using FeedVinc.WEB.UI.Models.ViewModels.InvesterLetter
@model List<ComingInvesterLetterVM>

@{
    Html.RenderAction("GetNavbar", "BaseUI");
}




<main>
    <section class="container min-height-700">
        <div class="row">
            <!-- Sol içerik -->
            <section class="col-lg-12 col-md-12 col-sm-12 col-xs-12 mb30">
                <div class="row">
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">


                        <div class="mentor-meeting-wrap">
                            <div class="w100 pull-left mb20">
                                <h1 class="pull-left">@SiteLanguage.InvestmentLetters</h1>
                            </div>
                            @foreach (var item in Model)
                            {
                                <div class="mentor-meeting">
                                    <div class="mentor-meeting-box">
                                        <p>@item.UserName - @item.ProjectName</p>
                                        <a href="/investment-letter/@item.LetterID" class="btn btn-default fs16 pull-right">@SiteLanguage.View</a>
                                    </div>
                                </div>
                            }
                        </div>



                    </div>
                </div>
            </section>
            <!-- Sol içerik bitti -->
        </div>
    </section>
</main>