FeedVinc.WEB.UI/Controllers/ProjectUIController.cs
using FeedVinc.Common.Services;
using FeedVinc.DAL.ORM.Entities;
using FeedVinc.WEB.UI.Models.DTO;
using FeedVinc.WEB.UI.Models.ViewModels.Account;
using FeedVinc.WEB.UI.Models.ViewModels.Home;
using FeedVinc.WEB.UI.Models.ViewModels.Project;
using FeedVinc.WEB.UI.Models.ViewModels.Project.Profile;
using FeedVinc.WEB.UI.Resources;
using FeedVinc.WEB.UI.UIServices;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FeedVinc.WEB.UI.Controllers
{
    public class ProjectUIController : BaseUIController
    {

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddLaunch(LaunchPostVM model)
        {

            if (ModelState.IsValid)
            {
                var entity = new ProjectLaunch
                {
                    Information = model.Information,
                    IsActive = true,
                    MediaPath = MediaManagerService.Save(new MediaFormatDTO { Media = model.Photo, MediaType = 0 }),
                    PostDate = DateTime.Now,
                    MediaTypeID = 0,
                    ProjectID = model.ProjectID,
                    ProjectVersion = model.Version,
                    ShareTypeID = 5,
                    WebLink = model.WebLink,
                    AppleLink = model.AppleLink,
                    AndroidLink = model.AndroidLink

                };

                services.projectLaunchRepo.Add(entity);
                services.Commit();


                return Json(new ValidationDTO { IsValid = true, SuccessMessage = SiteLanguage.Shared_your_Post });

            }

            var errorList = ModelState.Values.SelectMany(m => m.Errors)
                               .Select(e => new ValidationDTO { IsValid = false, ErrorMessage = e.ErrorMessage })
                               .ToList();

            return Json(new ValidationDTO { IsValid = false, Data = errorList });
        }

        [HttpPost]
        public ActionResult ProjectShare(SharePostVM model)
        {

            if (ModelState.IsValid)
            {
                if (model.MediaPhoto != null || model.MediaVideo != null)
                {
                    MediaFormatDTO mediaDTO = new MediaFormatDTO
                    {
                        MediaType = model.MediaPhoto != null ? 0 : 1,
                        Media = model.MediaPhoto != null ? model.MediaPhoto : model.MediaVideo,
                    };

                    model.MediaPath = MediaManagerService.Save(mediaDTO);
                    model.MediaTypeID = mediaDTO.MediaType;

                }

                var projectOwnerID = services.projectRepo.FirstOrDefault(y => y.ID == model.ProjectID).UserID;

                model.ShareTitle = SiteLanguage._STORY_TELLING;
                ProjectShare Projectshare = new ProjectShare
                {
                    Location = model.Location,
                    Content = model.Post,
                    ShareTypeID = model.ShareTypeID,
                    IsActive = true,
                    SharePath = model.MediaPath,
                    MediaType = (byte)model.MediaTypeID,
                    ShareDate = DateTime.Now,
                    ProjectID = model.ProjectID,
                    OwnerID = projectOwnerID

                };
                services.projectShareRepo.Add(Projectshare);
                int ID = services.Commit();


                SharePostDTO dto = new SharePostDTO
                {
                    FeedID = Projectshare.ID,
                    Post = model.Post,
                    Location = model.Location,
                    MediaPath = model.MediaPath,
                    MediaTypeID = model.MediaTypeID,
                    ShareTypeID = model.ShareTypeID,
                    ShareTitle = SiteLanguage.Around_Me,
                    User = services.appUserRepo.Where(a=> a.ID==projectOwnerID).Select(z=> new UserVM {

                        ID = z.ID,
                         FullName = z.Name + " " + z.SurName

                    }).FirstOrDefault(),
                    ProjectShare = services.projectRepo.Where(x => x.ID == model.ProjectID).Select(a => new ProjectSharePostDTO
                    {

                        ProjectName = a.ProjectName,
                        ProjectProfilePath = a.ProjectProfileLogo,
                        ProjectSlugify = a.ProjectSlugify,
                        ProjectID = a.ID

                    }).FirstOrDefault(),
                    PrettyDate = DateTimeService.GetPrettyDate(DateTime.Now, LanguageService.getCurrentLanguage),
                    Validation = new ValidationDTO { IsValid = true, SuccessMessage = SiteLanguage.Shared_your_Post }
                };

                return PartialView("~/Views/ProjectUI/ProjectProfilePartial/_projectAddedFeed.cshtml", dto);

            }


            return Json(new ValidationDTO { IsValid = false, ErrorMessage = SiteLanguage.Post_Validation });

        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddFeedBack(FeedBackPostVM model)
        {

            if (ModelState.IsValid)
            {
                var entity = new ProjectFeedBack();
                entity.FeedBackMedia = MediaManagerService.Save(new MediaFormatDTO { Media = model.Photo, MediaType = 0 });
                entity.Information = model.Information;
                entity.MediaTypeID = 0;
                entity.ProjectID = model.ProjectID;
                entity.TestLink = model.TestLink;
                entity.ShareTypeID = 4;
                entity.PostDate = DateTime.Now;
                entity.IsEnableNotifyInvestor = model.InformationEnabledInvestor;
                entity.IsActive = true;

                services.projectFeedBackRepo.Add(entity);
                services.Commit();

                return Json(new ValidationDTO { IsValid = true, SuccessMessage = SiteLanguage.Shared_your_Post });

            }

            var errorList = ModelState.Values.SelectMany(m => m.Errors)
                            .Select(e => new ValidationDTO { IsValid = false, ErrorMessage = e.ErrorMessage })
                            .ToList();

            return Json(new ValidationDTO { IsValid = false, Data = errorList });
        }


        public IEnumerable<SelectListItem> GetProjectStatusEN(byte? selectedProjectStatus = null)
        {
            var model = new List<SelectListItem>
            {
                new SelectListItem
                {
                     Text = SiteLanguage.Project_Status_Validation,
                     Value="0",
                     Selected = (selectedProjectStatus==0 ? true: false)
                },
                new SelectListItem
                {
                    Text ="Newer",
                    Value="1",
                    Selected = (selectedProjectStatus==1 ? true: false)
                },
                new SelectListItem
                {
                    Text ="Development of Phase",
                    Value="2",
                    Selected = (selectedProjectStatus==2 ? true: false)
                },
                new SelectListItem
                {
                    Text ="Ready for Publication",
                    Value="3",
                    Selected = (selectedProjectStatus==3 ? true: false)
                }

            };

            return model;
        }

        public IEnumerable<SelectListItem> GetProjectStatusTR(byte? selectedProjectStatus = null)
        {

            var model = new List<SelectListItem>
            {
                new SelectListItem
                {
                     Text = SiteLanguage.Project_Status_Validation,
                     Value="0",
                     Selected = (selectedProjectStatus==0 ? true: false)
                },
                new SelectListItem
                {
                    Text ="Yeni Başlandı",
                    Value="1",
                    Selected = (selectedProjectStatus==1 ? true: false)
                },
                new SelectListItem
                {
                    Text ="Geliştirme Aşamasında",
                    Value="2",
                    Selected = (selectedProjectStatus==2 ? true: false)

                },
                new SelectListItem
                {
                    Text ="Yayında Hazır",
                    Value="3",
                    Selected = (selectedProjectStatus==3 ? true: false)
                }

            };

            return model;

        }

        public IEnumerable<SelectListItem> GetInvestmentStatusEN(byte? selectedProjectInvestmentStatus = null)
        {
            var model = new List<SelectListItem>
            {
                new SelectListItem
                {
                     Text = SiteLanguage.Project_Investment_Status_Validation,
                     Value="0",
                     Selected = (selectedProjectInvestmentStatus==0 ? true: false)
                },
                new SelectListItem
                {
                    Text ="not invested.",
                    Value="1",
                    Selected = (selectedProjectInvestmentStatus==1 ? true: false)
                },
                new SelectListItem
                {
                    Text ="1st lap invested ",
                    Value="2",
                    Selected = (selectedProjectInvestmentStatus==2 ? true: false)
                },
                new SelectListItem
                {
                    Text ="2nd lap invested",
                    Value="3",
                    Selected = (selectedProjectInvestmentStatus==3 ? true: false)
                }

            };

            return model;

        }

        public IEnumerable<SelectListItem> GetInvestmentStatusTR(byte? selectedProjectInvestmentStatus = null)
        {

            var model = new List<SelectListItem>
            {
                new SelectListItem
                {

FeedVinc.WEB.UI/Views/ProjectUI/ProjectAdd.cshtml
@{
    ViewBag.Title = "ProjectAdd";
    Layout = "~/Views/Shared/_SiteLayout.cshtml";
}

@{
    Html.RenderAction("GetNavbar", "BaseUI");
}


@model ProjectPostVM


<main>
    <section class="container">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                @if (ViewBag.IsSuccess == true)
                { <div class="alert alert-success" style="font-size:xx-large;">@ViewBag.Success</div> }
            </div>

            @using (Html.BeginForm("ProjectAdd", "ProjectUI", FormMethod.Post, new { @enctype = "multipart/form-data", @id = "frmProjectAdd", @novalidate = "novalidate" }))
            {
                @Html.AntiForgeryToken()
                <section class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                    <div class="form-col">
                        <label for="project_name">@SiteLanguage.ProjectName</label>
                        @Html.TextBoxFor(x => x.ProjectName, new { @class = "inputs" })
                        <div class="text-danger text-center">@Html.ValidationMessageFor(x => x.ProjectName)</div>
                    </div>
                    <div class="form-col">
                        <label for="evelator_pitch">@SiteLanguage.Sales_Pitch</label>
                        @Html.TextAreaFor(x => x.SalesPitch, new { @class = "inputs" })
                        <div class="text-danger text-center">@Html.ValidationMessageFor(x => x.SalesPitch)</div>
                    </div>
                    <div class="form-col">
                        <div class="img-wrap">
                            <img src="@Model.ProjectProfileLogo" class="file_logo img-responsive">
                        </div>
                        @Html.TextBoxFor(x => x.ProjectPhoto, new { @type = "file", @class = "inputfile", @data_viewer_class = "file_logo" })
                    </div>
                    <div class="text-danger text-center">@Html.ValidationMessageFor(x => x.ProjectPhoto)</div>
                    <div class="form-col">
                        <div class="select">
                            @Html.DropDownListFor(x => x.CategoryID, (IEnumerable<SelectListItem>)ViewData["Category"])
                        </div>
                    </div>
                    <div class="text-danger text-center">@Html.ValidationMessageFor(x => x.CategoryID)</div>
                    <div class="form-col">
                        <div class="select">
                            @Html.DropDownListFor(x => x.CountryID, (IEnumerable<SelectListItem>)ViewData["Country"])
                        </div>
                    </div>
                    <div class="text-danger text-center">@Html.ValidationMessageFor(x => x.CountryID)</div>
                    <div class="form-col">
                        <div class="select">
                            @Html.DropDownListFor(x => x.CityID, (IEnumerable<SelectListItem>)ViewData["City"])
                        </div>
                    </div>
                    <div class="text-danger text-center">@Html.ValidationMessageFor(x => x.CityID)</div>
                    <div class="form-col">
                        <div class="select">
                            @Html.DropDownListFor(x => x.ProjectStatus, (IEnumerable<SelectListItem>)ViewData["ProjectStatus"])
                        </div>
                    </div>
                    <div class="text-danger text-center">@Html.ValidationMessageFor(x => x.ProjectStatus)</div>
                    <div class="form-col">
                        <div class="select">
                            @Html.DropDownListFor(x => x.ProjectInvestmentStatus, (IEnumerable<SelectListItem>)ViewData["InvestmentStatus"])
                        </div>
                    </div>
                    <div class="text-danger text-center">@Html.ValidationMessageFor(x => x.ProjectInvestmentStatus)</div>
                    <div class="form-col">
                        <label for="project_url">@SiteLanguage.Project_WebLink</label>
                        @Html.TextBoxFor(x => x.WebLink, new { @class = "inputs" })
                    </div>
                    <div class="form-col">
                        <label for="project_iphone_link">@SiteLanguage.Project_IPhoneLink</label>
                        @Html.TextBoxFor(x => x.AppleLink, new { @class = "inputs" })
                    </div>
                    <div class="form-col">
                        <label for="project_android_link">@SiteLanguage.Project_AndroidLink</label>
                        @Html.TextBoxFor(x => x.AndroidLink, new { @class = "inputs" })
                    </div>
                </section>
    <!-- Form sol kısım bitti -->
    <!-- Form sağ kısım -->
                <section class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                    <div class="form-col">
                        <label for="project_about">@SiteLanguage.Project_About</label>
                        @Html.TextAreaFor(x => x.About, new { @class = "textarea h100" })
                    </div>
                    <div class="form-col">
                        <label for="project_tags">@SiteLanguage.Project_Tags</label>
                        @Html.TextBoxFor(x => x.ProjectTags, new { @class = "inputs taginputs h100", @data_role = "tagsinput" })
                    </div>
                </section>
    <!-- Form sağ kısım bitti -->
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <button type="submit" name="gonder" class="btn btn-default pull-right mb30 fs21">@SiteLanguage.Project_Save</button>
                </div>
            }
        </div>
    </section>
</main>

@section scripts{

    <script src="~/Content/Site/assets/js/jquery-1.11.2.min.js"></script>
    <script src="~/Content/Site/assets/js/jquery.validate.min.js"></script>
    <script src="~/Content/Site/assets/js/jquery.validate.unobtrusive.min.js"></script>


}

FeedVinc.WEB.UI/Views/ProjectUI/ProjectEdit.cshtml
@{
    ViewBag.Title = "ProjectEdit";
    Layout = "~/Views/Shared/_SiteLayout.cshtml";
}


@{
    Html.RenderPartial("ProjectPartial/_projectNavbar", Model.ProjectMenu);
}


@model ProjectPostVM

<main>
    <section class="container">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                @if (ViewBag.IsSuccess == true)
                { <div class="alert alert-success" style="font-size:xx-large;">@ViewBag.Success</div> }
            </div>

            @using (Html.BeginForm("ProjectEdit", "ProjectUI", FormMethod.Post, new { @enctype = "multipart/form-data", @id = "frmProjectAdd", @novalidate = "novalidate" }))
            {
                @Html.AntiForgeryToken()
                @Html.HiddenFor(x=> x.ID)
                @Html.HiddenFor(x=> x.ProjectProfileLogo)
                <section class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                    <div class="form-col">
                        <label for="project_name">@SiteLanguage.ProjectName</label>
                        @Html.TextBoxFor(x => x.ProjectName, new { @class = "inputs" })
                        <div class="text-danger text-center">@Html.ValidationMessageFor(x => x.ProjectName)</div>
                    </div>
                    <div class="form-col">
                        <label for="evelator_pitch">@SiteLanguage.Sales_Pitch</label>
                        @Html.TextAreaFor(x => x.SalesPitch, new { @class = "inputs" })
                        <div class="text-danger text-center">@Html.ValidationMessageFor(x => x.SalesPitch)</div>
                    </div>
                    <div class="form-col">
                        <div class="img-wrap">
                            <img src="@Model.ProjectProfileLogo" class="file_logo img-responsive">
                        </div>
                        @Html.TextBoxFor(x => x.ProjectPhoto, new { @type = "file", @class = "inputfile", @data_viewer_class = "file_logo" })
                    </div>
                    <div class="text-danger text-center">@Html.ValidationMessageFor(x => x.ProjectPhoto)</div>
                    <div class="form-col">
                        <div class="select">
                            @Html.DropDownListFor(x => x.CategoryID, (IEnumerable<SelectListItem>)ViewData["Category"])
                        </div>
                    </div>
                    <div class="text-danger text-center">@Html.ValidationMessageFor(x => x.CategoryID)</div>
                    <div class="form-col">
                        <div class="select">
                            @Html.DropDownListFor(x => x.CountryID, (IEnumerable<SelectListItem>)ViewData["Country"])
                        </div>
                    </div>
                    <div class="text-danger text-center">@Html.ValidationMessageFor(x => x.CountryID)</div>
                    <div class="form-col">
                        <div class="select">
                            @Html.DropDownListFor(x => x.CityID, (IEnumerable<SelectListItem>)ViewData["City"])
                        </div>
                    </div>
                    <div class="text-danger text-center">@Html.ValidationMessageFor(x => x.CityID)</div>
                    <div class="form-col">
                        <div class="select">
                            @Html.DropDownListFor(x => x.ProjectStatus, (IEnumerable<SelectListItem>)ViewData["ProjectStatus"])
                        </div>
                    </div>
                    <div class="text-danger text-center">@Html.ValidationMessageFor(x => x.ProjectStatus)</div>
                    <div class="form-col">
                        <div class="select">
                            @Html.DropDownListFor(x => x.ProjectInvestmentStatus, (IEnumerable<SelectListItem>)ViewData["InvestmentStatus"])
                        </div>
                    </div>
                    <div class="text-danger text-center">@Html.ValidationMessageFor(x => x.ProjectInvestmentStatus)</div>
                    <div class="form-col">
                        <label for="project_url">@SiteLanguage.Project_WebLink</label>
                        @Html.TextBoxFor(x => x.WebLink, new { @class = "inputs" })
                    </div>
                    <div class="form-col">
                        <label for="project_iphone_link">@SiteLanguage.Project_IPhoneLink</label>
                        @Html.TextBoxFor(x => x.AppleLink, new { @class = "inputs" })
                    </div>
                    <div class="form-col">
                        <label for="project_android_link">@SiteLanguage.Project_AndroidLink</label>
                        @Html.TextBoxFor(x => x.AndroidLink, new { @class = "inputs" })
                    </div>
                </section>
    <!-- Form sol kısım bitti -->
    <!-- Form sağ kısım -->
                <section class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                    <div class="form-col">
                        <label for="project_about">@SiteLanguage.Project_About</label>
                        @Html.TextAreaFor(x => x.About, new { @class = "textarea h100" })
                    </div>
                    <div class="form-col">
                        <label for="project_tags">@SiteLanguage.Project_Tags</label>
                        @Html.TextBoxFor(x => x.ProjectTags, new { @class = "inputs taginputs h100", @data_role = "tagsinput" })
                    </div>
                </section>
    <!-- Form sağ kısım bitti -->
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <button type="submit" name="gonder" class="btn btn-default pull-right mb30 fs21">@SiteLanguage.Project_Save</button>
                </div>
            }
        </div>
    </section>
</main>

@section scripts{

    <script src="~/Content/Site/assets/js/jquery-1.11.2.min.js"></script>
    <script src="~/Content/Site/assets/js/jquery.validate.min.js"></script>
    <script src="~/Content/Site/assets/js/jquery.validate.unobtrusive.min.js"></script>

}

FeedVinc.WEB.UI/Views/ProjectUI/ProjectPhotoEdit.cshtml
@{
    ViewBag.Title = "ProjectPhotoEdit";
    Layout = "~/Views/Shared/_SiteLayout.cshtml";
}

@model ProjectPhotoVM


@{
    Html.RenderPartial("ProjectPartial/_projectNavbar", Model.Menu);
}



<main>
    <section class="container min-height-700">
        <div class="row">
            <div class="project-images-edit">
                <div class="mb20">
                    <div id="loading"></div>
                    @using (Html.BeginForm("ProjectPhotoEdit", "ProjectUI", FormMethod.Post, new { @id = "frmPictureAdd", @enctype = "multipart/form-data" }))
                    {
                        @Html.AntiForgeryToken()
                        <input type="file" name="Files" multiple class="add-image" data-viewer-class="file-logo">
                        <input type="hidden" name="ProjectID" value="@ViewBag.ProjectID" />
                        <input type="submit" name="gonder" value="@SiteLanguage.Post_Button" class="btn btn-default fs21 pull-right" />
                    }

                </div>
                @foreach (var item in Model.ProjectPhotos)
                {
                    <div class="img-box" id="photo_@item.ID">
                        <img src="@item.PhotoPath" class="img-responsive">
                        <a href="Delete(@item.ID)" class="img-delete-btn">
                            <i class="fa fa-remove"></i>
                        </a>
                    </div>
                    <div id="img-json">

                    </div>
                }
            </div>
        </div>
    </section>
</main>

@section scripts{

    <script src="~/Content/Site/assets/js/jquery.validate.min.js"></script>
    <script src="~/Content/Site/assets/js/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/Content/Site/assets/js/jquery.unobtrusive-ajax.min.js"></script>
    <script src="~/Content/Site/assets/js/jquery.form.min.js"></script>

    <script>
        toastr.options = {
            "closeButton": false,
            "debug": false,
            "newestOnTop": false,
            "progressBar": false,
            "positionClass": "toast-bottom-full-width",
            "showDuration": "300",
            "hideDuration": "1000",
            "timeOut": "5000",
            "extendedTimeOut": "1000",
            "showEasing": "swing",
            "hideEasing": "linear",
            "showMethod": "fadeIn",
            "hideMethod": "fadeOut"
        };
    </script>

    <script>
        $('#frmPictureAdd').ajaxForm({
            clearForm: true,
            resetForm: true,
            beforeSubmit: function () {
                var target = document.getElementById('loading');
                $(target).show();
                var spinner = new Spinner().spin();
                target.appendChild(spinner.el);
            },
            success: function (response) {
                if (response.IsValid) {
                    $.each(response.Data, function (key, value) {
                        $("#img-json").append('<div class="img-box" id="photo_' + value.ID + '"><img src="' + value.PhotoPath + '" class="img-responsive"><a href="Delete(' + value.ID + ')" class="img-delete-btn"><i class="fa fa-remove"></i></a></div>');
                    });
                }
                else {
                    toastr.error(response.ErrorMessage);
                }


                console.log(response);
                var target = document.getElementById('loading');
                $(target).hide();
            }
        });
    </script>

}

FeedVinc.WEB.UI/Views/ProjectUI/ProjectVideoEdit.cshtml
@{
    ViewBag.Title = "ProjectVideoEdit";
    Layout = "~/Views/Shared/_SiteLayout.cshtml";
}

@model ProjectVideoVM


@{
    Html.RenderPartial("ProjectPartial/_projectNavbar", Model.Menu);
}

<main>
    <section class="container min-height-700">
        <div class="row">
            <div class="project-images-edit">
                <div class="mb20">
                    <div id="loading"></div>
                    @using (Html.BeginForm("ProjectVideoEdit", "ProjectUI", FormMethod.Post, new { @id = "frmVideoAdd", @enctype = "multipart/form-data" }))
                    {
                        @Html.AntiForgeryToken()
                        <input type="file" name="Files" multiple class="add-image" data-viewer-class="file-logo">
                        <input type="hidden" name="ProjectID" value="@ViewBag.ProjectID" />
                        <input type="submit" name="gonder" value="@SiteLanguage.Post_Button" class="btn btn-default fs21 pull-right" />
                    }

                </div>
                @foreach (var item in Model.ProjectVideos)
                {

                    <div class="img-box video-box videoModal" data-toggle="modal" data-target="#videoModal_@item.ID">
                        <span class="video-box--overlay"></span>
                        <a onclick="openModal(@item.ID,'@item.VideoPath')"><img src="~/Content/Site/assets/images/video-install-button@2x.png" class="img-responsive video-box--img"></a>
                        <a href="#" class="img-delete-btn video-box--btn">
                            <i class="fa fa-remove"></i>
                        </a>
                    </div>

                }

                <div id="video-json">

                </div>
            </div>
        </div>
    </section>
</main>





@foreach (var item in Model.ProjectVideos)
{

    <div class="modal fade videoModal" id="videoModal_@item.ID" tabindex="-1" role="dialog" aria-labelledby="videoModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                </div>
                <div class="modal-body">
                    <video width="100%" class="projectVideo" controls>
                        <source src="@item.VideoPath">
                        <source src="@item.VideoPath" type="video/ogg"> Your browser does not support HTML5 video.
                    </video>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default"  data-dismiss="modal">@SiteLanguage.Close</button>
                </div>
            </div>
        </div>
    </div>

}





@section scripts{

    <script src="~/Content/Site/assets/js/jquery.form.min.js"></script>

    <script>

        var videoID = null;
        var source = null;

        function openModal(id, src) {
            videoID = id;
            source = src;
        }

        $('.videoModal').on('hidden.bs.modal', function (e) {
            $(".projectVideo").attr("src", source);
        });



    </script>
    <script>
        toastr.options = {
            "closeButton": false,
            "debug": false,
            "newestOnTop": false,
            "progressBar": false,
            "positionClass": "toast-bottom-full-width",
            "showDuration": "300",
            "hideDuration": "1000",
            "timeOut": "5000",
            "extendedTimeOut": "1000",
            "showEasing": "swing",
            "hideEasing": "linear",
            "showMethod": "fadeIn",
            "hideMethod": "fadeOut"
        };
    </script>

    <script>
        $('#frmVideoAdd').ajaxForm({
            clearForm: true,
            resetForm: true,
            beforeSubmit: function () {
                var target = document.getElementById('loading');
                $(target).show();
                var spinner = new Spinner().spin();
                target.appendChild(spinner.el);
            },
            success: function (response) {
                if (response.IsValid) {
                    $.each(response.Data, function (key, value) {

                        $("#video-json").append(' <div class="img-box video-box videoModal" data-toggle="modal" data-target="#videoModal_'+value.ID+'"><span class="video-box--overlay"></span><a onclick=\"openModal('+value.ID+',\''+value.VideoPath+'\')\"><img src="/Content/Site/assets/images/video-install-button@2x.png" class="img-responsive video-box--img"></a><a href="#" class="img-delete-btn video-box--btn"><i class="fa fa-remove"></i></a></div>');

                        $(document.body).append('<div class="modal fade videoModal" id="videoModal_' + value.ID + '" tabindex="-1" role="dialog" aria-labelledby="videoModalLabel"><div class="modal-dialog" role="document"><div class="modal-content"><div class="modal-header"><button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button></div> <div class="modal-body"><video width="100%" class="projectVideo" controls><source src="' + value.VideoPath + '"> <source src="' + value.VideoPath + '" type="video/ogg"> Your browser does not support HTML5 video.</video></div><div class="modal-footer"><button type="button" class="btn btn-default" onclick="close()" data-dismiss="modal">@SiteLanguage.Close</button></div></div></div></div>');
                    });
                }
                else {
                    toastr.error(response.ErrorMessage);
                }


                console.log(response);
                var target = document.getElementById('loading');
                $(target).hide();
            }
        });
    </script>




}