FeedVinc.WEB.UI/Controllers/AccountUIController.cs
using FeedVinc.Common.Services;
using FeedVinc.DAL.ORM.Entities;
using FeedVinc.WEB.UI.Models.ViewModels.Account;
using FeedVinc.WEB.UI.Models.ViewModels.UserProfile;
using FeedVinc.WEB.UI.Resources;
using FeedVinc.WEB.UI.UIServices;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;

namespace FeedVinc.WEB.UI.Controllers
{
    public class AccountUIController : BaseUIController
    {


        [HttpPost]
        [OverrideActionFilters]
        public JsonResult Login(LoginVM model)
        {
            var user = UserManagerService.HasAccount(model.Email, model.Password);

            if (user != null)
            {
                CookieManagerService.SetCookie("ApplicationUser", user.ID.ToString());   

                return Json(new { message = SiteLanguage.RedirectMessage, RedirectURL = "/home", IsValid = true, UserID = "UserID=" + user.ID });
            }

            return Json(new { message = SiteLanguage.Login_Error, IsValid = false });

        }

        [HttpGet]
        [OverrideActionFilters]
        public ActionResult UserActivation(string activationCode)
        {
            var model = services.appUserRepo.FirstOrDefault(x => x.UserGUID == activationCode);
            model.IsActive = true;
            services.Commit();

            return Redirect("/index");
        }

        [HttpPost]
        [OverrideActionFilters]
        public JsonResult Register(RegisterVM model)
        {

            if (!UserManagerService.UserNameIsCorrectFormat(model.FullName))
            {
                ModelState.AddModelError("FullName", SiteLanguage.FullName_Pattern_Error);
            }

            if (!UserManagerService.EmailIsUnique(model.Email))
            {
                ModelState.AddModelError("Email", SiteLanguage.EmailUnique_Validation);
            }

            if (ModelState.IsValid)
            {
                var user = new ApplicationUser
                {
                    Name = model.FullName.Split(' ')[0].Capitalize(),
                    SurName = model.FullName.Split(' ')[1].ToUpper(),
                    Email = model.Email,
                    Password = model.Password,
                    UserGUID = Guid.NewGuid().ToString(),
                    UserTypeID = model.UserTypeID,
                    UserSlugify = SlugIfyService.SlugText(model.FullName),
                    UserCode = RandomCodeGenerator.Generate()

                };

                services.appUserRepo.Add(user);
                services.Commit();

                string subject = "FeedVinc | " + SiteLanguage.Membership_Confirmation;
                string body = string.Empty;
                using (StreamReader reader = new StreamReader(Server.MapPath("~/Content/Template/activate.html")))
                {
                    body = reader.ReadToEnd();
                }

                body = body.Replace("{HELLO}", SiteLanguage.Email_Hello);
                body = body.Replace("{WELCOME}", SiteLanguage.Welcome);
                body = body.Replace("{CONTENT}", SiteLanguage.Email_Activation_Body);
                body = body.Replace("{WARNING}", SiteLanguage.Email_Activation_Warning);
                body = body.Replace("{URL}", "http://feedvinc.workstudyo.com/activate-account/" + user.UserGUID);
                body = body.Replace("{NAME}", user.Name);
                body = body.Replace("{LINK}", SiteLanguage.Activate_Link);

                List<MailAddress> toList = new List<MailAddress>();
                toList.Add(new MailAddress(user.Email, user.Name + " " + user.SurName, System.Text.Encoding.UTF8));

                string logoPath = Server.MapPath(@"~/Content/Template/FeedVinc_Logo.png");

                EmailService.SendMail(toList, null, null, subject, body, logoPath);
                return Json(new { message = SiteLanguage.Register_Success, IsValid = true });


            }

            var errorList = ModelState.Values.
               SelectMany(m => m.Errors).
               Select(e => e.ErrorMessage).
               ToList();

            return Json(new { error = errorList, IsValid = false });
        }


        [HttpPost]
        [OverrideActionFilters]
        public JsonResult ForgetPassword(ForgetPasswordVM modal)
        {
            var user = services.appUserRepo.FirstOrDefault(x => x.Email == modal.Email);
            user.Password = System.Web.Security.Membership.GeneratePassword(8, 1);
            services.Commit();

            if (user != null)
            {
                string subject = "FeedVinc | " + SiteLanguage.Forget_Password;
                string body = string.Empty;
                using (StreamReader reader = new StreamReader(Server.MapPath("~/Content/Template/activate.html")))
                {
                    body = reader.ReadToEnd();
                }

                body = body.Replace("{HELLO}",SiteLanguage.Email_Hello);
                body = body.Replace("{LINK}", SiteLanguage.WebSiteLink);
                body = body.Replace("{WELCOME}", "");
                body = body.Replace("{URL}", "http://feedvinc.workstudyo.com/");
                body = body.Replace("{NAME}", user.Name);
                body = body.Replace("{CONTENT}", SiteLanguage.Password_Reset_Warning_Message + "<p><span>Password : "+user.Password+"</span></p>");
                body = body.Replace("{WARNING}", SiteLanguage.Email_Activation_Warning);

                List<MailAddress> toList = new List<MailAddress>();
                toList.Add(new MailAddress(user.Email, user.Name + " " + user.SurName, System.Text.Encoding.UTF8));

                string logoPath = Server.MapPath(@"~/Content/Template/FeedVinc_Logo.png");

                bool IsSend = EmailService.SendMail(toList, null, null, subject, body, logoPath);
                return Json(new { message = SiteLanguage.Forget_Password_Success, IsValid = true });
            }


            return Json(new { error = SiteLanguage.Forget_Password_User_not_Found, IsValid = false });


        }

        [HttpGet]
        public ActionResult LogOut()
        {
            CookieManagerService.DeleteCookie("ApplicationUser");
            return Redirect("/index");
        }
    }
}

FeedVinc.WEB.UI/Views/HomeUI/IndexPartial/Modals/_forgetPassModal.cshtml
@model ForgetPasswordVM

<div class="remodal" data-remodal-id="password-modal" role="dialog" aria-labelledby="passwordTitle" aria-describedby="passwordDesc">
    <button data-remodal-action="close" class="remodal-close" aria-label="Kapat"></button>
    <div>
        <div id="loadingPasswordReset"></div>
        <h2 id="passwordTitle">@SiteLanguage.Forget_Password !</h2>

        @using (Ajax.BeginForm("ForgetPassword", "AccountUI", null, new AjaxOptions { HttpMethod = "Post", OnSuccess = "OnPasswordResetSuccess", OnComplete = "OnPasswordResetComplete", OnBegin = "OnPasswordResetBegin", OnFailure = "OnPasswordResetFailure" }, new { @class = "loginForm" }))
        {
            <div>
                <label for="forgot_password_email">@SiteLanguage.Email</label>
                <br />
                <span class="text-danger">@Html.ValidationMessageFor(x => x.Email)</span>
                @Html.TextBoxFor(x => x.Email)
            </div>
            <div class="w100">
                <a href="#login-modal" class="forgot-password">@SiteLanguage.Login</a>
                <button type="submit" class="btn btn-default remodal-confirm">@SiteLanguage.Send_Password</button>
            </div>
        }
    </div>
</div>

<script>

    function OnPasswordResetBegin() {
        var target = document.getElementById('loadingPasswordReset');
        var spinner = new Spinner().spin();
        target.appendChild(spinner.el);
    }

    function OnPasswordResetComplete() {
        var target = document.getElementById('loadingPasswordReset');
        $(target).hide();
    }

    function OnPasswordResetSuccess(response) {

        if (response.IsValid) {
            toastr.success(response.message);
            setTimeout(function () {
                toastr.clear();
            }, 3000);
        }
        else if (response.IsValid == false) {
            toastr.error(response.error);
        }
       
    }
    
    function OnPasswordResetFailure(error) {
        console.log(error.message)
    }

</script>

FeedVinc.WEB.UI/Views/HomeUI/IndexPartial/Modals/_loginModal.cshtml
@model LoginVM

<div class="remodal" data-remodal-id="login-modal" role="dialog" aria-labelledby="girisyapTitle" aria-describedby="girisyapDesc">
    <button data-remodal-action="close" class="remodal-close" aria-label="Kapat"></button>
    <div>
        <div id="loadingLogin"></div>
        <h2 id="girisyapTitle">@SiteLanguage.Login</h2>

        @using (Ajax.BeginForm("Login", "AccountUI", null, new AjaxOptions { OnSuccess = "OnLoginSuccess", OnBegin = "OnLoginBegin", OnFailure = "OnLoginFailure", OnComplete = "OnLoginComplete" }, new { @class = "loginForm", @novalidate = "novalidate", @name = "loginForm", @id = "loginForm" }))
        {
            <span id="AccountIsValid" class="text-danger"></span>
            <div>
                <label for="email">@SiteLanguage.Email</label>
                @Html.TextBoxFor(x => x.Email)
            </div>
            <div>
                <label for="password">@SiteLanguage.Password</label>
                @Html.TextBoxFor(x => x.Password, new { @type = "Password" })
            </div>
            <div class="w100">
                <a href="#password-modal" class="forgot-password">@SiteLanguage.Forget_Password</a>
                <button type="submit" class="btn btn-default remodal-confirm">@SiteLanguage.Login</button>
            </div>
        }
        <div class="text-center">
            <a href="#register-modal" class="register-now">@SiteLanguage.Has_Not_Account</a>
        </div>
    </div>
</div>

<script>

    function OnLoginBegin() {
        var target = document.getElementById('loadingLogin');
        var spinner = new Spinner().spin();
        target.appendChild(spinner.el);
    }

    function OnLoginFailure(error) {
        console.log(error.message);
    }

    function OnLoginSuccess(response) {


        if (response.IsValid == false) {
            toastr.error(response.message);

        }
        else if (response.IsValid == true) {
            $("#loginForm").trigger("reset");
            toastr.success(response.message);

            setTimeout(function () {
                toastr.clear();
                window.location.href = response.RedirectURL;
            }, 2000)
        }
    }

    function OnLoginComplete() {
        var target = document.getElementById('loadingLogin');
        $(target).hide();
    }
</script>

FeedVinc.WEB.UI/Views/HomeUI/IndexPartial/Modals/_registerModal.cshtml
@model RegisterVM

<div class="remodal" data-remodal-id="register-modal" role="dialog" aria-labelledby="kayitolTitle" aria-describedby="kayitolDesc">
    <button data-remodal-action="close" class="remodal-close" aria-label="Kapat"></button>
    <div>
        <h2 id="girisyapTitle">@SiteLanguage.Register</h2>
        <div id="loadingRegister"></div>

        @using (Ajax.BeginForm("Register", "AccountUI",null, new AjaxOptions { HttpMethod = "Post", OnSuccess = "OnRegisterSuccess", OnBegin = "OnRegisterBegin",OnComplete = "OnRegisterComplete", OnFailure= "OnRegisterFailure" }, new { @class = "registerForm",@novalidate="novalidate",@id="frmRegister" }))
        {
            <div>

                <label for="adsoyad">@SiteLanguage.FullName</label>
                <br />
                <span class="text-danger">@Html.ValidationMessageFor(x => x.FullName)</span>
                @Html.TextBoxFor(x=> x.FullName)
            </div>
            <div>
                <label for="email">@SiteLanguage.Email</label>
                <br />
                <span class="text-danger">@Html.ValidationMessageFor(x => x.Email)</span>
                @Html.TextBoxFor(x=> x.Email)
            </div>
            <div>
                <label for="password">@SiteLanguage.Password</label>
                <br />
                <span class="text-danger">@Html.ValidationMessageFor(x => x.Password)</span>
                @Html.TextBoxFor(x => x.Password,new {@type="password" })
            </div>
            <div>
                <label for="password">@SiteLanguage.Password_Again</label>
                <br />
                <span class="text-danger">@Html.ValidationMessageFor(x => x.PasswordConfirm)</span>
                @Html.TextBoxFor(x=> x.PasswordConfirm, new {@type= "password"})
            </div>
            <div>
                <label for="usertype">@SiteLanguage.UserType</label>
                <div class="select-user-type">
                    <select name="UserTypeID" class="usertype">
                        <option value="3">@SiteLanguage.Entrepreneur</option>
                        <option value="2">@SiteLanguage.Financier</option>
                        <option value="1">@SiteLanguage.Developer</option>
                    </select>
                </div>
            </div>
            <div class="w100">
                <button type="submit" class="btn btn-default remodal-confirm">@SiteLanguage.Register</button>
            </div>
        }

        <div class="text-center">
            <a href="#login-modal" class="register-now">@SiteLanguage.Has_Account_Login</a>
        </div>
    </div>
</div>

<script>
    function OnRegisterBegin() {
        var target = document.getElementById('loadingRegister');
            var spinner = new Spinner().spin();
            target.appendChild(spinner.el);
    }

    function OnRegisterFailure(error) {
        console.log(error.message);
    }

    function OnRegisterSuccess(response) {
        if (response.IsValid == false) {
            toastr.error(response.error);
            toastr.options.closeDuration = 300;
        }
        else {
            toastr.success(response.message);
            setTimeout(function () {
                toastr.clear();
                window.location.href = "/index";
            }, 3000);
        }
    }

    function OnRegisterComplete() {
        var target = document.getElementById('loadingRegister');
        $(target).hide();
    }
</script>